// swift-tools-version:5.9
import PackageDescription

// Generated by scripts/render-swift-package.sh. For local binding development
// use bindings/swift/Package.swift instead of this distribution manifest.
let nativeVersion = "1.2.7"
let nativeChecksum = "41c9b1cce2544c463d34057b786dbe0ea6cfd399a6a7ba8c7a7ec83117df3036"
let nativeURL = "https://github.com/agentstatelabs/agentstategraph/releases/download/v\(nativeVersion)/agentstategraph-swift-v\(nativeVersion).xcframework.zip"

let package = Package(
    name: "AgentStateGraph",
    platforms: [
        .macOS(.v11),
        .iOS(.v14),
    ],
    products: [
        .library(name: "AgentStateGraph", targets: ["AgentStateGraph"]),
    ],
    targets: [
        .binaryTarget(
            name: "AgentStateGraphFFI",
            url: nativeURL,
            checksum: nativeChecksum
        ),
        .target(
            name: "AgentStateGraph",
            dependencies: ["AgentStateGraphFFI"],
            path: "bindings/swift/Sources/AgentStateGraph",
            linkerSettings: [
                .linkedLibrary("c++"),
                .linkedFramework("Security"),
                .linkedFramework("CoreFoundation"),
            ]
        ),
        .testTarget(
            name: "AgentStateGraphTests",
            dependencies: ["AgentStateGraph"],
            path: "bindings/swift/Tests/AgentStateGraphTests"
        ),
    ]
)
