#!/usr/bin/env bash
#
# Render the root SwiftPM distribution manifest after the release XCFramework
# exists and its checksum is known. The nested bindings/swift/Package.swift is
# intentionally retained for local dylib/XCFramework development.
set -euo pipefail

[ $# -ge 2 ] && [ $# -le 3 ] || {
  echo "usage: $0 <version> <sha256> [output]" >&2
  exit 2
}

VERSION="${1#v}"
CHECKSUM="$2"
OUTPUT="${3:-Package.swift}"
GITHUB_REPO="${GITHUB_REPO:-agentstatelabs/agentstategraph}"

echo "$VERSION" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+([-.][0-9A-Za-z.-]+)?$' || {
  echo "error: invalid version '$VERSION'" >&2
  exit 2
}
echo "$CHECKSUM" | grep -Eq '^[0-9a-f]{64}$' || {
  echo "error: checksum must be 64 lowercase hexadecimal characters" >&2
  exit 2
}
echo "$GITHUB_REPO" | grep -Eq '^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$' || {
  echo "error: invalid GITHUB_REPO '$GITHUB_REPO'" >&2
  exit 2
}

cat > "$OUTPUT" <<EOF
// swift-tools-version:5.9
import PackageDescription

// Generated by scripts/render-swift-package.sh. For local binding development
// use bindings/swift/Package.swift instead of this distribution manifest.
let nativeVersion = "$VERSION"
let nativeChecksum = "$CHECKSUM"
let nativeURL = "https://github.com/$GITHUB_REPO/releases/download/v\(nativeVersion)/agentstategraph-swift-v\(nativeVersion).xcframework.zip"

let package = Package(
    name: "AgentStateGraph",
    platforms: [
        .macOS(.v11),
        .iOS(.v14),
    ],
    products: [
        .library(name: "AgentStateGraph", targets: ["AgentStateGraph"]),
    ],
    targets: [
        .binaryTarget(
            name: "AgentStateGraphFFI",
            url: nativeURL,
            checksum: nativeChecksum
        ),
        .target(
            name: "AgentStateGraph",
            dependencies: ["AgentStateGraphFFI"],
            path: "bindings/swift/Sources/AgentStateGraph",
            linkerSettings: [
                .linkedLibrary("c++"),
                .linkedFramework("Security"),
                .linkedFramework("CoreFoundation"),
            ]
        ),
        .testTarget(
            name: "AgentStateGraphTests",
            dependencies: ["AgentStateGraph"],
            path: "bindings/swift/Tests/AgentStateGraphTests"
        ),
    ]
)
EOF

echo "rendered $OUTPUT for AgentStateGraph v$VERSION"
